apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  greeting: "Hello, World!"
  message: "Welcome to Kubernetes ConfigMaps"
  config.txt: |
    This is a multi-line
    configuration file
    stored in a ConfigMap
